#!/bin/sh
MD=..
TD=$MD/lib/Audio/Ecasound/Multitrack
./preproc -r Audio::Ecasound::Multitrack \
		-s $MD/pre \
		-t $TD \
		-a p \
		-b pm 
mv $TD/Multitrack.pm $TD/../Multitrack.pm 
./preproc  -s $MD/pre \
         -t $MD/t  \
		 -r Audio::Ecasound::Multitrack \
		 -a t \
		 -b t
