---
abstract: ~
author:
  - 'Joel Roth, <joelz@pobox.com>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Audio-Ecasound-Multitrack
no_index:
  directory:
    - inc
    - t
requires:
  Audio::Ecasound: 0
  Carp: 0
  Cwd: 0
  Data::Rmap: 0
  Data::YAML: 0
  Event: 0
  File::Find::Rule: 0
  File::Spec::Link: 0
  Getopt::Std: 0
  IO::All: 0
  Module::Load::Conditional: 0
  Parse::RecDescent: 0
  Storable: 0
  Term::ReadLine: 0
  Term::ReadLine::Gnu: 0
  Text::Format: 0
  Time::HiRes: 0
  perl: 5.10.0
version: 0.9980
