#!/usr/bin/env perl
use v5.38;
use Modern::Perl;
use feature qw(isa);
use Tickit;
use Tickit::Console;
use Tickit::Widgets qw(Static Entry ScrollBox VBox);
use Tickit::Widget::Entry::Plugin::History;
use Tickit::Widget::Entry::Plugin::Completion;
my $label;
my $entry;
my $scroller;
use DDP;
my $console = Tickit::Console->new( 
#	tab_class => 'Tickit::Widget::ScrollBox',
   on_line => sub {
      	my ( $self, $line ) = @_;
		$scroller->push(Tickit::Widget::Scroller::Item::Text->new($line));
		$scroller->scroll_to_bottom;
		prompt();
   	},
	);
my $panel = $console->add_tab(name => 'Nama/Ecasound');
my $tabbed = find_first($console, 'Tickit::Widget::Tabbed');
$scroller = find_first($tabbed, 'Tickit::Widget::Scroller');
$entry = find_first($console, 'Tickit::Widget::Entry');

sub find_first {
	my ($obj, $wanted_class) = @_;
	my @children = $obj->children;
	my ($first) = grep{ $_ isa  $wanted_class } @children;
	$first;
}
	

 $scroller->push(
            Tickit::Widget::Scroller::Item::Text->new( "Hello world" ),
            Tickit::Widget::Scroller::Item::Text->new( "Here are some lines" ),
            map { Tickit::Widget::Scroller::Item::Text->new( "<Line $_>" ) } 1 .. 50,
          );
          

$console->add( $label = Tickit::Widget::Static->new( text => "What you just typed appears here." ) );

sub prompt {
	my $prompt = 'enter command > ';
	$entry->set_text($prompt);
	$entry->set_position(99);
}
 
Tickit::Widget::Entry::Plugin::Completion->apply( $entry,
   words => [ 'this','that','those','them'],
);

#Tickit::Widget::Entry::Plugin::History->apply( $entry ); # breaks prompt (set_text/set_position)

my $tickit = Tickit->new( root => $console);


$console->bind_key('M-Home', 
	sub{ 	my($console,$key) = @_;
			$scroller->scroll_to_top;
		} );
$console->bind_key('M-End', 
	sub{ 	my($console,$key) = @_;
			$scroller->scroll_to_bottom;
		} );
$tickit->run

