---
wav_dir: /media/sessions
abbreviations:
  24-mono: s24_le,1,frequency
  32-10: s32_le,10,frequency
  32-12: s32_le,12,frequency
  cd-mono: s16_le,1,44100
  cd-stereo: s16_le,2,44100,i
  frequency: 44100
devices:
  jack:
    ecasound_id: jack_alsa
    input_format: 32-12
    output_format: 32-10
  multi:
    ecasound_id: alsa,ice1712
    input_format: 32-12
    output_format: 32-10
  stereo:
    ecasound_id: alsa,default
    input_format: cd-stereo
    output_format: cd-stereo
ecasound_globals: "-B auto"
mix_to_disk_format: cd-stereo
mixer_out_format: cd-stereo
raw_to_disk_format: cd-mono
ladspa_sample_rate: frequency
unit: 1 				
effects_cache_file: effects_cache.storable
state_store_file: State 
chain_setup_file: project.ecs
tk_input_channels: 10
use_monitor_version_for_mixdown: true 
alias:
  1: Mixdown
  2: Tracker
...
