#!/usr/bin/env perl
my $list = qx(./strip_all ./commands);
map{

	chomp;
	my @parts = my @all_parts = split " ", $_;
	my $full = shift @parts;
	my @short = @parts;
	push @abbrevs,	"_$full: '" . join ("' | '" , @all_parts). "'";
	push @stubs,   	"$full: _$full {}";
	push @commands,	"command: $full";

} split "\n", $list;

print join "\n", @commands, @abbrevs, @stubs ;
__END__
