#!/usr/bin/env perl
#use Test::More qw(no_plan);
use lib qw(.. .); 
use UI;
$UI::wav_dir = '/media/projects';
$UI::project_name = 'paul_brocante';
=comment
my $s = UI::Project->new(name => 'paul_brocante');
is(defined $s, 1, "Project instantiation" ); 
is( $s->isa('UI::Project'),1, "Parent class for ". ref $s);
is( $s->project_dir , '/media/projects/.ecmd/paul_brocante', "Directory shows");
=cut
my $wav = UI::Wav->new( n => 5, head => 'sax');
print "n: ", $wav->n;
print join $/, %{ $wav->targets} or die;
print join $/, @{ $wav->versions} or die;
print join ".".$/, %{ UI::Wav::targets("sax")} or die;
#is(defined $wav, 1, "Project instantiation" ); 
#is( $wav->isa('UI::Wav'),1, "Parent class for ". ref $s);
#diag( print join $/, %{ $wav->targets });



__END__

