#!/usr/bin/env perl
use lib '/home/jroth/build/flow/lib';
use Getopt::Std;
use Audio::Ecasound::Flow;

package Audio::Ecasound::Flow::UI;
$debug =1;
$debug2 =1;
### Option Processing ###
use vars qw(%opts $session_name $debug);
@ARGV = qw(-g -m -e paul_brocante);
getopts('mcdeg', \%opts); 
$session_name = shift;
$debug and print "session name: $session_name\n";
my $ui = Audio::Ecasound::Flow::UI::Graphical->new();
$ui->prepare;
$ui->loop;
#&prepare;
#&loopg;


