#!/usr/bin/env perl
use warnings;
use lib qw(.. .); 
package UI;
use UI;
use Getopt::Std;
#use vars qw(%opts $project $debug);
my $debug = 1;
### Option Processing ###
push @ARGV, qw(-g -e -d /media/projects paul_brocante);
getopts('mcegsd:', \%opts); 
#print join $/, (%opts);
# d: wav_dir
# c: create project
# g: gui mode
# m: don't load state info
# e: don't load static effects data
$project = shift;
$debug and print "project name: $project\n";
$project and $project_name = $project;
my $ui = UI::Text->new;
$ui->prepare; 
$ui->loop;
__END__

