#!/bin/sh
TD=../lib/Audio/Ecasound/Multitrack 
PD=.
preproc -r Audio::Ecasound::Multitrack \
		-s ~/build/flow/Audio-Multitrack/pre \
		-t $TD
mv $TD/Multitrack.pm $TD/../Multitrack.pm 
preproc  -s ~/build/flow/Audio-Multitrack/pre \
         -t ~/build/flow/Audio-Multitrack/t    \
		 -r Audio::Ecasound::Multitrack \
		 -a t \
		 -b t
