#!/bin/sh
# if the executable contains 'src', then we assume top-level
IS_TOP_LEVEL=`echo $0 | grep src`;
if [ $IS_TOP_LEVEL ]; then
	cd src
fi
./myproc
cd ..
./Build.PL
echo "Now you can go to the nama toplevel directory and type:"
echo "\t./Build test"
echo "If you're happy with the result you can do:"
echo "\t./Build install"
echo "****************************************"
if [ ! $IS_TOP_LEVEL ]; then
	cd src 
fi
