#!/bin/sh
./myproc
cd ..
perl Makefile.PL
echo "Now you can go to the nama toplevel directory and type:"
echo "\tmake; make test"
echo "If you're happy with the result you can do:"
echo "\tmake install"
echo "****************************************"
