#!/usr/bin/env perl
use v5.36;
use Path::Tiny;
# get registered keys by combining contents of two files 
my %var_map = map{ split " ", $_ } split "\n", qx(./strip_all ./var_config);
my @vars1 = values %var_map;
my @vars2 = split "\n", qx(./strip_all ./var_keys);
my %singletons;
my %singleton_has_key; 
{no warnings 'uninitialized';

map{ 
	my $target = $_;
	my ($singleton, $key) = $target =~ /^(\$\w+)->\{(\w+)}/;
	
	{
		#say "singleton: $singleton, key: $key";
		$singletons{$singleton}++;
		$singleton_has_key{$singleton} //= {};
		$singleton_has_key{$singleton}{$key}++;
	}
} @vars1, @vars2
}
my @files = glob("*.p *.pl *.t");
=begin comment

use Data::Dumper::Concise;
print Dumper \%singletons;
print Dumper \%singleton_has_key;

print join " ", @files;

=end comment

=cut

my $srevars = join '|', map{ s/\$//; $_ } keys %singletons;
my $sre = qr/\$($srevars)->\{(\w+)}/;

map{ 
	my $filename = $_;
	my $contents = path($filename)->slurp_raw;
	while( $contents =~ /$sre/g )
	{
		my($singleton,$key) = ($1,$2);
		#say "found $singleton, $key";
		say "$filename: illegal key ", $singleton, '->{', $key , '}'
			if ! $singleton_has_key{"\$$singleton"}{$key}
	}
} @files;
