#!/usr/bin/env perl
use v5.36;
use Path::Tiny;
use Text::Template;
use autodie;

my $script_dir = '../bin';
mkdir $script_dir unless -d $script_dir;
my $script = "$script_dir/nama";
my $exec = <<EXEC;
#!/usr/bin/env perl
use Audio::Nama;
Audio::Nama::main();
__END__
EXEC

my @man;
my $man_template = Text::Template->new(
	TYPE       => 'FILE',
	SOURCE     => 'man_page_part1',
	DELIMITERS => [qw([% %])],
);
my $part1 = $man_template->fill_in;
die "Unable to expand man_page_part1\n" unless defined $part1;
push @man, $part1, "\n";
my $tail = path('man_page_part2')->slurp_raw;
my ($operation, $back_matter) = split /(?=^=head1 BUGS)/m, $tail, 2;
die "Unable to split man_page_part2 at BUGS\n" unless defined $back_matter;
push @man, $operation, "\n";
push @man, "=head1 COMMAND REFERENCE\n\n";
push @man, qx(./emit_command_headers pod);
push @man, $back_matter;
path($script)->spew_raw($exec, @man);
chmod 0755, $script;
