#!/bin/sh
# use -d for debugging output

# change to build directory nama/src

CUR_DIR=`dirname $0`
cd "$CUR_DIR"

./check_hash_keys

MD=..
LIBPATH=$MD/lib/Audio/Nama
LD=$MD/lib
TD=$MD/t
SD=$MD/script

./missing_files_list

echo "Cleaning output directories"
for d in $LD $SD; do rm -rf $d; mkdir -p $d; done
rm $TD/*.t
mkdir -p $LIBPATH

DEBUG=$1
./preproc $DEBUG -r Nama \
		-s $MD/src \
		-t $LIBPATH \
		-a p \
		-b pm 
mv $LIBPATH/Nama.pm $LIBPATH/../Nama.pm 
./preproc $DEBUG -s $MD/src \
         -t $MD/t  \
		 -r Nama \
		 -a t \
		 -b t
./generate_executable_stub
cp makeman $MD/lib/Audio
cd $MD/lib/Audio
./makeman
rm *.tmp
cd ../../src
