#!/bin/sh
# use -d for debugging output

./check_hash_keys
#./sort_vars > variables.sorted.txt
MD=..
TD=$MD/lib/Audio/Nama
TESTD=$MD/t

./missing_files_list

echo "Cleaning output directories"
rm -rf $TD
rm -rf $TESTD
CUR_DIR=`dirname $0`
cd "$CUR_DIR"
if [ ! -d $TD ]; then
   mkdir -p $TD;
fi
if [ ! -d $TESTD ]; then
   mkdir -p $TESTD;
fi
DEBUG=$1
./preproc $DEBUG -r Audio::Nama \
		-s $MD/src \
		-t $TD \
		-a p \
		-b pm 
mv $TD/Nama.pm $TD/../Nama.pm 
./preproc $DEBUG -s $MD/src \
         -t $MD/t  \
		 -r Audio::Nama \
		 -a t \
		 -b t
./generate_executable_stub
cp makeman $MD/lib/Audio
cd $MD/lib/Audio
./makeman
rm *.tmp
cd ../../src
#cd ..
#perl Makefile.PL
echo "Now you can go to the nama toplevel directory and type:"
echo -e "\tmake; make test"
echo "If you're happy with the result you can do:"
echo -e "\tmake install"
echo "****************************************"
