#!/usr/bin/env perl
use File::Slurp;
my @files = @ARGV;
map{ print strip_all(read_file($_)) } @files;
sub strip_all{ strip_blank_lines( strip_comments(@_) ) }

sub strip_blank_lines {
	map{ s/\n(\s*\n)+/\n/sg } @_;
	@_;
	 
}

sub strip_comments { #  
	map{ s/#.*$//mg; } @_;
	@_
} 
