#!/usr/bin/perl
$/ = undef;
my $in = <>;
print strip_all($in);
sub strip_all{ strip_blank_lines( strip_comments(@_) ) }

sub strip_blank_lines {
	map{ s/\n(\s*\n)+/\n/sg } @_;
	@_;
	 
}

sub strip_comments { #  
	map{ s/#.*$//mg; } @_;
	@_
} 
