#!/usr/bin/env perl
use Path::Tiny;
my @files = @ARGV;
map{ print strip_all(my $string = path($_)->slurp_raw) } @files;
sub strip_all{ strip_blank_lines( strip_comments(@_) ) }

sub strip_blank_lines {
	map{ s/\n(\s*\n)+/\n/sg } @_;
	@_;
	 
}

sub strip_comments { #  
	map{ s/#.*$//mg; } @_;
	@_
} 
